version: 2
jobs:
  build:
    
    working_directory: ~/ciricleCI_appium_java

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/node:4.8.2
      - image: mongo:3.4.4

    steps:

      - checkout

      - restore_cache:
          key: ciricleCI_appium_java-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: ciricleCI_appium_java-{{ checksum "pom.xml" }}
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      
      # run tests!
      - run:     
               mvn test

      - store_artifacts:
          path: target/surefire-reports
          destination: tr1
      - store_test_results:
          path: target/surefire-reports

