machine:
  node:
    version: 0.12
  ruby:
    version: 2.3.0
  pre:
    - wget http://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo mv -f chromedriver /usr/local/bin

dependencies:
  pre:
    - gem install bundler
    - npm install appium

test:
  override:
    #bootup emulator
    - emulator -avd circleci-android24 -no-audio -no-window:
        background: true
        parallel: true
    # wait for it to have booted
    - circle-android wait-for-boot
    - sleep 5
    #unlock the device
    - adb shell input keyevent 82
    - sleep 5
    - adb shell input touchscreen swipe 370 735 371 735
    - sleep 5
    #start appium server
    - appium:
        background: true
    - mvn package
